### ISSUE TITLE
Unanticipated host error without Windows microphone permission

### ISSUE THREAD

**Issue by ileben** [PortAudio/portaudio#360]
(Please use the mailing list for support requests and general discussion. This is only for actual bugs.)

**Describe the bug**
I'am using PortAudio via Caster python package which uses Dragonfly, which uses Sounddevice (0.3.15), which uses PortAudio (not sure which version). On startup, I get the error below, unless I manually enable microphone permissions in Windows settings. I am running Microsoft Windows 10 Enterprise 10.0.18363 Build 18363. It would be nice to check for this and provide a better error message.

```
Traceback (most recent call last):
  File "C:\Python27-64bit\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27-64bit\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27-64bit\lib\site-packages\dragonfly\__main__.py", line 408, in <module>
    main()
  File "C:\Python27-64bit\lib\site-packages\dragonfly\__main__.py", line 403, in main
    return_code = func(args)
  File "C:\Python27-64bit\lib\site-packages\dragonfly\__main__.py", line 174, in cli_cmd_load
    with engine.connection():
  File "C:\Python27-64bit\lib\site-packages\dragonfly\engines\base\engine.py", line 50, in __enter__
    self._engine.connect()
  File "C:\Python27-64bit\lib\site-packages\dragonfly\engines\backend_kaldi\engine.py", line 197, in connect
    reconnect_callback=self._options['audio_reconnect_callback'],
  File "C:\Python27-64bit\lib\site-packages\dragonfly\engines\backend_kaldi\audio.py", line 228, in __init__
    super(VADAudio, self).__init__(**kwargs)
  File "C:\Python27-64bit\lib\site-packages\dragonfly\engines\backend_kaldi\audio.py", line 75, in __init__
    self._connect(start=start)
  File "C:\Python27-64bit\lib\site-packages\dragonfly\engines\backend_kaldi\audio.py", line 89, in _connect
    callback=proxy_callback if not self.self_threaded else None,
  File "C:\Python27-64bit\lib\site-packages\sounddevice.py", line 1153, in __init__
    **_remove_self(locals()))
  File "C:\Python27-64bit\lib\site-packages\sounddevice.py", line 861, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "C:\Python27-64bit\lib\site-packages\sounddevice.py", line 2651, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening RawInputStream: Unanticipated host error [PaErrorCode -9999]: 'Undefined external error.' [MME error 1]
```

This is what I had to do to resolve the issue:

![image](https://user-images.githubusercontent.com/370626/101269252-25f59780-37c1-11eb-8d05-7f479c616884.png)

**Comment by RossBencina** [comment]
@ileben do you know which host APIs this affects (e.g. WASAPI, DirectSound, WMME)? If possible, are you able to test each of them? Also, can you dump the hosterror_info struct, that will display what the underlying host API error code is.

**Comment by RossBencina** [comment]
I agree that a better error message would be nice. The traceback indicates that the error being returned is:

> Unanticipated host error [PaErrorCode -9999]: 'Undefined external error.' [MME error 1]

MME itself is returning `Undefined external error` - we can't translate that to anything more meaningful.  Maybe other native  APIs provide better error codes.

A possible fix would be to interrogate the system about whether the process has microphone permissions for the particular device. I don't know whether that's possible.

We do not currently have a `PaError` code for "permission error". That seems fundamental in 2022.
