### ISSUE TITLE
OSError: [Errno -9986] Internal PortAudio error

### ISSUE THREAD

**Issue by fabihoern** [PortAudio/portaudio#430]
Hi,

I'm programming with PortAudio / PyAudio. I installed the library with homebrew. On my windows Pc I never got this error.
**Desktop**
 - OS: Mac OS
 - OS Version: Big Sur 11.1
 - PortAudio version: latest
 - PyCharm

Simple sr code:
import speech_recognition as sr

r = sr.Recognizer()
mic = sr.Microphone()
with mic as source:
    r.adjust_for_ambient_noise(source)
    audio = r.listen(source)
    transcript = r.recognize_google(audio)
    print(transcript)

I always got this error:

||PaMacCore (AUHAL)|| Error on line 1277: err='-66748', msg=Unknown Error
Traceback (most recent call last):
  File "/Users/fabianhoernlein/Desktop/testsr/main.py", line 6, in <module>
    with mic as so
  File "/Users/fabianhoernlein/Desktop/testsr/venv/lib/python3.9/site-packages/speech_recognition/__init__.py", line 138, in __enter__
    self.audio.open(
  File "/Users/fabianhoernlein/Desktop/testsr/venv/lib/python3.9/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/Users/fabianhoernlein/Desktop/testsr/venv/lib/python3.9/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9986] Internal PortAudio error

Process finished with exit code 1

I tryed a lot around packages, reinstall, update, ...
 thx for help,
Fabi

**Comment by arkwad** [comment]
HI,
I have a similar Issue on
- OS: Mac OS
- OS Version: Big Sur 11.1
- PortAudio version: latest

||PaMacCore (AUHAL)|| Error on line 1277: err='-66748', msg=Unknown Error
Traceback (most recent call last):
  File "/Users/arkwad/githome/dsp/./audio_sampler.py", line 7, in <module>
    myrecording = sd.rec(int(seconds * fs), samplerate=fs, channels=1)
  File "/usr/local/lib/python3.9/site-packages/sounddevice.py", line 274, in rec
    ctx.start_stream(InputStream, samplerate, ctx.input_channels,
  File "/usr/local/lib/python3.9/site-packages/sounddevice.py", line 2573, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
  File "/usr/local/lib/python3.9/site-packages/sounddevice.py", line 1415, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/usr/local/lib/python3.9/site-packages/sounddevice.py", line 892, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/usr/local/lib/python3.9/site-packages/sounddevice.py", line 2738, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Internal PortAudio error [PaErrorCode -9986]


I tried to run guest Ubuntu VM under VirtualBox with passing input audio to it and works as expected there so it is something specific for MacOS.

Please take a look as probably ppl have a similar problem

//Arek

**Comment by arkwad** [comment]
I believe also this is a duplicated issue as https://github.com/PortAudio/portaudio/issues/395 looks the same

**Comment by philburk** [comment]
Yes, this is a DUP of #395
A fix is pending in #356

**Comment by arkwad** [comment]
Actually based on comments from other connected issues: 
`brew uninstall portaudio &&  brew install portaudio --HEAD` worked for me as WA
